baseURL = "https://Orama-Studio.github.io/site/"
languageCode = "it-it"
title = "Orama"

[[module.mounts]]
  source = "assets"
  target = "assets"

[[module.mounts]]
  source = "node_modules"
  target = "assets/node_modules"
